[versions]
agp = "8.13.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
kspPlugin = "2.2.20-2.0.4"

materialIconsExtended = "1.7.8"
materialVersion = "1.13.0"

# Coil
coilCompose = "2.7.0"
coilGif = "2.7.0"
coil = "3.3.0"

# Koin
koinAndroid = "4.1.1"

# Serialization
kotlinxSerializationJson = "1.9.0"
kotlinSerialization = "2.2.21"

# Coroutines
kotlinxCoroutines = "1.10.2"

# Network
pagingCompose = "3.3.6"
retrofit = "3.0.0"
loggingInterceptor = "5.3.0"
converterGson = "3.0.0"

# Room
roomRuntime = "2.8.3"

# Navigation
nav3Core = "1.0.0-alpha10"
lifecycleViewmodelNav3 = "1.0.0-alpha04"

# Pager
pagerVersion = "1.9.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }

androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }

androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }

foundation-pager = { group = "androidx.compose.foundation", name = "foundation", version.ref = "pagerVersion" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Image Porter
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilGif" }

# Coroutines
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

# Navigation
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }

# Room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

# Network
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }

# DI
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koinAndroid" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroid" }

[bundles]
compose = [
    "androidx-activity-compose",

    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-material3",

    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview"
]

network = [
    "retrofit",
    "logging-interceptor",
    "converter-gson"
]

navigation = [
    "androidx-navigation3-runtime",
    "androidx-navigation3-ui",

    "androidx-lifecycle-viewmodel-navigation3",
    "foundation-pager"
]

database = [
    "androidx-room-runtime",
    "androidx-room-paging",
    "androidx-room-ktx"
]

coroutines = [
    "kotlinx-coroutines-android",
    "kotlinx-coroutines-core"
]

general = [
    "androidx-material-icons-extended",
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",

    "material",
    "kotlinx-serialization-json",
    "koin-androidx-compose"
]

coil = [
    "coil-network-okhttp",
    "coil-compose",
    "coil-gif"
]

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization"}
